### ISSUE TITLE
Help needed regarding setup

### ISSUE THREAD

**Issue by abhi18av** [voldikss/vim-mma#2]
Hi @voldikss , 

First off, thank you for this fork - I was really looking for something like this for so long!

I just run across a problem regarding the `code completion`, which is not working at all.

Here are the contents of my `init.vim`

```vim
call plug#begin('~/.local/share/nvim/plugged')

Plug 'voldikss/vim-mma'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/neco-syntax'

:tnoremap <Esc> <C-\><C-n>

" Initialize plugin system
call plug#end()


"let g:mma_candy = 1
"let g:mma_candy = 2

```

I'm trying to use the `m` and `nb` extension but I seem to be missing something 

```
nvim ~/projects/code/_scratch/scratch.nb

nvim ~/projects/code/_scratch/scratch.m
```

Could you please help me out a bit?

**Comment by voldikss** [comment]
Thanks for pointing that out.
Actually I just tested the syntax completion on coc.nvim and I ever thought it
will also work with deoplete.nvim... But it seems that I was wrong.
Don't worry, I am going to test it tomorrow (cus it is 23:41 here) and give
you an answer.

Abhinav Sharma <notifications@github.com> 于 2019年5月29日周三 下午11:32写道：

**Comment by voldikss** [comment]
Hi @abhi18av I just revert the workable version for deoplete.nvim. I tested on my laptop and it works, you may update and have a try

**Comment by abhi18av** [comment]
Hi @voldikss , I'm used `Plug#update()` for updating the plugins but I unable to see any noticeable changes as of now. 

If it's too much work I could move to `coc.nvim` as you seem to use it more, personally

**Comment by voldikss** [comment]
It's strange, I used the latest deoplete.nvim and this works on my laptop...

> If it's too much work I could move to coc.nvim as you seem to use it more, personally

Yes I know, switching is unrealistic

**Comment by voldikss** [comment]
> I'm used Plug#update() for updating the plugins

is this vim-plug's command? which plugin manager do you use?

**Comment by abhi18av** [comment]
Whoops,  I made a mistake, the command I used is `PlugInstall` and `PlugUpdate`.

Also, I've installed and tried now with `coc` as well but the result is the same. What do you suggest I could do to move forward?

**Comment by voldikss** [comment]
Hmmm, I just tested again with coc.nvim and it works for me.

> What do you suggest I could do to move forward?

Run `nvim test.nb` and type `:echo &filetype` to see if the `*.nb` file is recognized as `mma`

**Comment by abhi18av** [comment]
@voldikss , yup it shows `mma` as you mentioned.

**Comment by abhi18av** [comment]
You think it might be because of the `neovim` version I might be using? 
It's `0.3.5` 

Could you tell me how I could start from scratch?

**Comment by voldikss** [comment]
Sorry but...I think I could not help you with this anymore. Things are strange 😂

IMO other editors or IDEs such as VSCode/IntelliJ will be more suitable for you to write Wolfram code.

**Comment by abhi18av** [comment]
Ah well, I think that we've both tried our best as well. Anyways, I want to thank you @voldikss for being so responsive and patient with your efforts and also for this wonderful fork - it'd be useful for many people 😊

**Comment by voldikss** [comment]
Sorry but...I think I could not help you with this anymore. Things are
strange 😂

IMO other editors or IDEs such as VSCode/IntelliJ will be more suitable for
you to write Wolfram code.

Abhinav Sharma <notifications@github.com> 于 2019年5月31日周五 上午12:04写道：
